apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-rest-mvc
  name: spring-rest-mvc
spec:
  type: NodePort
  ports:
  - name: 8071-8071
    port: 8071
    protocol: TCP
    targetPort: 8071
  selector:
    app: spring-rest-mvc
status:
  loadBalancer: {}
