apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-rest-mvc
  name: spring-rest-mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-rest-mvc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-rest-mvc
    spec:
      containers:
      - image: joheiss/spring6-rest-mvc
        name: spring6-rest-mvc
        resources: {}
        env:
        - name: LOGGING_LEVEL_COM_JOVISCO
          value: info
        - name: LOGGING_LEVEL_ORG_HIBERNATE_SQL
          value: warn
        - name: LOGGING_LEVEL_ORG_ZALANDO_LOGBOOK
          value: info
        - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
          value: "true"
        - name: MANAGEMENT_HEALTH_READINESS_STATE_ENABLED
          value: "true"
        - name: MANAGEMENT_HEALTH_LIVENESS_STATE_ENABLED
          value: "true"
        - name: SERVER_SHUTDOWN
          value: graceful
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        readinessProbe:
          httpGet:
            port: 8071
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8071
            path: /actuator/health/liveness
status: {}
