@baseUrl = http://localhost:8071
@url = {{baseUrl}}/api/v1
@auth = user1:password
@token = eyJraWQiOiIxMzgyMzY4OC1hMWMxLTQ1MmYtODRkZS0wNDNlMTA0MjNiNmEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvaWRjLWNsaWVudCIsImF1ZCI6Im9pZGMtY2xpZW50IiwibmJmIjoxNzE3MzQ1Mjk5LCJzY29wZSI6WyJtZXNzYWdlLnJlYWQiLCJtZXNzYWdlLndyaXRlIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcxNzM0NTU5OSwiaWF0IjoxNzE3MzQ1Mjk5LCJqdGkiOiI3ODJlOGZiZS1jM2ZjLTQ5ZGEtYTM4My03ZjIyNmQxN2MwY2MifQ.Saz9Yw4VLNwvcCMltqO4sj7187qYYWWJonn4cLxKEE1tjOTscrp_pPBG0d6pUxyZ5FBuKISfqGxUuTN3HqHb-1UcA8U9wE0elnuNyNH3pMXUJg4eIYCEtUXPICyVNnuiRUC3tWAzgUyhsSxNoZEk7Yyz6jLhjGa7AuzhYGOBGu1pt_9y5Y4xP2Kusn7LxIxSX89AO5UMeRgZ3kJ9bVk__2kd2xB5arElrUhz2GIE2rtQTt5AUjfub4GDdADesVGM91P0bGT96ey7goYszX0PYg0DcH_1QvEJ_51qPRntm9SPWlSELNNkRrQ8zRkdKK2pkg54YtVnut64jT8CGKfghA

# health check (actuator)

GET {{baseUrl}}/actuator/health 

###

# kubernetes probe for readiness (actuator)

GET {{baseUrl}}/actuator/health/readiness

###

# kubernetes probe for liveliness (actuator)

GET {{baseUrl}}/actuator/health/liveness

###

# GET list of beers
GET {{url}}/beers
Authorization: Bearer {{token}}
Content-Type: application/json

###

# GET list of beers with name and style
GET {{url}}/beers?name=IPA&style=IPA
Authorization: Bearer {{token}}
Content-Type: application/json

###

# GET beer by id
GET {{url}}/beers/c6928bcf-f185-4e29-997e-02150f2e5c99
Authorization: Bearer {{token}}
Content-Type: application/json

###

# POST beer
POST {{url}}/beers
Content-Type: application/json

{
    "name": "Andechser Dunkel",
    "style": "STOUT",
    "upc": "471112",
    "quantityOnHand": 210,
    "price": 12.76
}

###

# PUT beer
PUT {{url}}/beers/dffe54cc-5025-4977-b5bc-2c50f2df4679
Content-Type: application/json

{
    "name": "Erdinger Weizen *UPDATED*"
}

###

# DELETE beer by id
DELETE {{url}}/beers/d18cc4ad-fd7a-470b-be83-a01f76ad818f

###

# PATCH beer
PATCH {{url}}/beers/9b6abf8d-4032-4d11-b918-f52cf5077a31
Content-Type: application/json

{
    "price": 13.24
}

###

# GET list of customers
GET {{url}}/customers
Content-Type: application/json
Authorization: Bearer {{token}}

###

# GET customer by Id
GET {{url}}/customers/c0a8b289-8fd8-114a-818f-d9bf7d9c6c95
Authorization: Bearer {{token}}

###

# POST customer
POST {{url}}/customers
Content-Type: application/json

{
    "name": "Gschaftlhuber KG"
}

###

# PUT customer by id
PUT {{url}}/customers/8735b308-dfa2-4153-babf-aa74fb82e53e
Content-Type: application/json

{
    "name": "Klosterfrau GmbH & Co KG"
}

###

# DELETE customer by id
DELETE {{url}}/customers/f6a137c4-cccd-42db-9970-d3b210e22cde

###

# PATCH customer by id
PATCH {{url}}/customers/1ed8dcd2-c835-44ca-9c46-0ff8d35f70bc
Content-Type: application/json

{
    "version": 2
}

###

# GET list of beers
GET {{url}}/orders
Authorization: Bearer {{token}}
Content-Type: application/json

###