@baseUrl = http://localhost:8071
@url = {{baseUrl}}/api/v1
@auth = user1:password
@token = eyJraWQiOiJiYjZhZjc1YS0zNWEwLTQ3NTAtOTUyMy0wYTE1YWYyMzNjYmYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvaWRjLWNsaWVudCIsImF1ZCI6Im9pZGMtY2xpZW50IiwibmJmIjoxNzE3MjUwNjc5LCJzY29wZSI6WyJtZXNzYWdlLnJlYWQiLCJtZXNzYWdlLndyaXRlIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcxNzI1MDk3OSwiaWF0IjoxNzE3MjUwNjc5LCJqdGkiOiIzMWZkZDA2OS1kNTk1LTQxYWYtYWM3My02ZjgyOTQ3Y2YzZDIifQ.EzCK2g800zHI0TbM526jStQw9ZnJraJrzZGbR4Eik2nm2kNsLv_OpMYhdPPgRgl_Gg4_oqhclpXv46zQcrhINZLWjxogv-_2i-G1456ehlUTJV0lV-XQbKRkE78-ofUMNnc4xhmNdc_4tI-Ia5j-7xrMWZzPPSASmEChm-LTrqkb7JO7dxbJkjoq79Y-iiyGD13t4yCLDIZoDraZ_1bv8kAOCitwnhJHpPSYKU2ZIaxxPGhGPSt4AYfZ3uRzAqCDkMlxA7aX36uCmiLkDGioS8BF7mqcDh0tm6V83EOjqzgSxyuPrtGP3Mq2EwNnvAs_nPKUkUSr5ALou7GpUTrgPQ

# health check (actuator)

GET {{baseUrl}}/actuator/health 

###

# kubernetes probe for readiness (actuator)

GET {{baseUrl}}/actuator/health/readiness

###

# kubernetes probe for liveliness (actuator)

GET {{baseUrl}}/actuator/health/liveness

###

# GET list of beers
GET {{url}}/beers
Authorization: Bearer {{token}}
Content-Type: application/json

###

# GET list of beers with name and style
GET {{url}}/beers?name=IPA&style=IPA
Authorization: Bearer {{token}}
Content-Type: application/json

###

# GET beer by id
GET {{url}}/beers/c6928bcf-f185-4e29-997e-02150f2e5c99
Authorization: Bearer {{token}}
Content-Type: application/json

###

# POST beer
POST {{url}}/beers
Content-Type: application/json

{
    "name": "Andechser Dunkel",
    "style": "STOUT",
    "upc": "471112",
    "quantityOnHand": 210,
    "price": 12.76
}

###

# PUT beer
PUT {{url}}/beers/dffe54cc-5025-4977-b5bc-2c50f2df4679
Content-Type: application/json

{
    "name": "Erdinger Weizen *UPDATED*"
}

###

# DELETE beer by id
DELETE {{url}}/beers/d18cc4ad-fd7a-470b-be83-a01f76ad818f

###

# PATCH beer
PATCH {{url}}/beers/9b6abf8d-4032-4d11-b918-f52cf5077a31
Content-Type: application/json

{
    "price": 13.24
}

###

# GET list of customers
GET {{url}}/customers
Content-Type: application/json

###

# GET customer by Id
GET {{url}}/customers/e87db851-9b6c-4699-873f-2b3b33ae35a3

###

# POST customer
POST {{url}}/customers
Content-Type: application/json

{
    "name": "Gschaftlhuber KG"
}

###

# PUT customer by id
PUT {{url}}/customers/8735b308-dfa2-4153-babf-aa74fb82e53e
Content-Type: application/json

{
    "name": "Klosterfrau GmbH & Co KG"
}

###

# DELETE customer by id
DELETE {{url}}/customers/f6a137c4-cccd-42db-9970-d3b210e22cde

###

# PATCH customer by id
PATCH {{url}}/customers/1ed8dcd2-c835-44ca-9c46-0ff8d35f70bc
Content-Type: application/json

{
    "version": 2
}

###
