@baseUrl = http://localhost:8071
@url = {{baseUrl}}/api/v1
@auth = user1:password
@token = eyJraWQiOiI1YTZhMWJiMS01ZjZlLTQ5YzItYjczNS03MjAzZmZlMzRkZmMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvaWRjLWNsaWVudCIsImF1ZCI6Im9pZGMtY2xpZW50IiwibmJmIjoxNzE3NDM0NTg1LCJzY29wZSI6WyJtZXNzYWdlLnJlYWQiLCJtZXNzYWdlLndyaXRlIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcxNzQzNDg4NSwiaWF0IjoxNzE3NDM0NTg1LCJqdGkiOiIwNzJkOTFhZi1kMWY3LTRiNzQtYWU5OS03YTQ1OTgyZTdlZDEifQ.FDRF9Z1lRmoz3CrEdCuYdbpBlyQfShfEBeZWA9vTBvgIEb_qimfpvvY0qUZNElhrtVz3Pco7tH3EPtHi-X_vxHNL1niqpip1n3PFZ6xAsqZwaJwgL8GWWT1xZMt4db7P35gQ1kKlxO0-PJpI0pFkwH0I0z-uhknrLjBAmdMwdGJ9g8SsY3bvZ-PdYXlaanp7rkC6oIMqticp4ZNt_5iyw4J0SBvIkZGq-u9aV_gEzvQdOpiR_R5fjhJGdPQt1WMykKmqZgChzAFOWULHz496WuScKBJ9ut3Eo2uuSnedzm5bWCZepZ5ULCAAa9rM6b6LKcTJH5eKBNpcR0WNdvleZw

GET {{baseUrl}}/actuator/health 

###

# health check on dynamic port (kubernetes NodePort)
GET http://localhost:32465/actuator/health

###
GET http://localhost:32465/actuator/health/readiness

###
GET http://localhost:32465/actuator/health/liveness

###

# kubernetes probe for readiness (actuator)

GET {{baseUrl}}/actuator/health/readiness

###

# kubernetes probe for liveliness (actuator)

GET {{baseUrl}}/actuator/health/liveness

###

# GET list of beers
GET {{url}}/beers
Authorization: Bearer {{token}}
Content-Type: application/json

###

# GET list of beers with name and style
GET {{url}}/beers?name=IPA&style=IPA
Authorization: Bearer {{token}}
Content-Type: application/json

###

# GET beer by id
GET {{url}}/beers/c6928bcf-f185-4e29-997e-02150f2e5c99
Authorization: Bearer {{token}}
Content-Type: application/json

###

# POST beer
POST {{url}}/beers
Content-Type: application/json

{
    "name": "Andechser Dunkel",
    "style": "STOUT",
    "upc": "471112",
    "quantityOnHand": 210,
    "price": 12.76
}

###

# PUT beer
PUT {{url}}/beers/dffe54cc-5025-4977-b5bc-2c50f2df4679
Content-Type: application/json

{
    "name": "Erdinger Weizen *UPDATED*"
}

###

# DELETE beer by id
DELETE {{url}}/beers/d18cc4ad-fd7a-470b-be83-a01f76ad818f

###

# PATCH beer
PATCH {{url}}/beers/9b6abf8d-4032-4d11-b918-f52cf5077a31
Content-Type: application/json

{
    "price": 13.24
}

###

# GET list of customers
GET {{url}}/customers
Content-Type: application/json
Authorization: Bearer {{token}}

###

# GET customer by Id
GET {{url}}/customers/c0a8b289-8fd8-114a-818f-d9bf7d9c6c95
Authorization: Bearer {{token}}

###

# POST customer
POST {{url}}/customers
Content-Type: application/json

{
    "name": "Gschaftlhuber KG"
}

###

# PUT customer by id
PUT {{url}}/customers/8735b308-dfa2-4153-babf-aa74fb82e53e
Content-Type: application/json

{
    "name": "Klosterfrau GmbH & Co KG"
}

###

# DELETE customer by id
DELETE {{url}}/customers/f6a137c4-cccd-42db-9970-d3b210e22cde

###

# PATCH customer by id
PATCH {{url}}/customers/1ed8dcd2-c835-44ca-9c46-0ff8d35f70bc
Content-Type: application/json

{
    "version": 2
}

###

# GET list of orders
GET {{url}}/orders
Authorization: Bearer {{token}}
Content-Type: application/json

###

# DELETE order by id
DELETE {{url}}/orders/c0a8b289-8fdd-1819-818f-dd81f7d138d6
Authorization: Bearer {{token}}

###
